# Generated by Django 5.2.17 on 2026-09-06 16:30

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, max_length=120)),
                ('event_title', models.CharField(max_length=255)),
                ('participant_name', models.CharField(max_length=255)),
                ('avantika_email', models.EmailField(db_index=True, max_length=254, validators=[core.models.validate_avantika_email])),
                ('enrollment_id', models.CharField(blank=True, max_length=64, null=True)),
                ('department_year', models.CharField(blank=True, max_length=120, null=True)),
                ('team_size', models.PositiveSmallIntegerField(default=1)),
                ('synced_to_sheet', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PitchSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('founder_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('startup_name', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=120)),
                ('one_line_pitch', models.TextField()),
                ('ref_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
